### ISSUE TITLE
No issues associated with milestone

### ISSUE THREAD

**Issue by Marsup** [hapijs/hapijs.com#287]
```
Debug: internal, implementation, error
    TypeError: Cannot read property 'length' of undefined
    at exports.routes.push.config.handler (lib/routes.js:63:44)
    at Object.internals.handler (node_modules/hapi/lib/handler.js:94:36)
    at node_modules/hapi/lib/handler.js:60:30
    at done (node_modules/hapi/node_modules/items/lib/index.js:30:25)
    at done (node_modules/hapi/node_modules/items/lib/index.js:63:25)
    at node_modules/hapi/lib/handler.js:47:28
    at finalize (node_modules/hapi/lib/handler.js:279:20)
    at wrapped (node_modules/hoek/lib/index.js:798:20)
    at internals.Response._processPrepare (node_modules/hapi/lib/response.js:418:16)
    at internals.Response._prepare (node_modules/hapi/lib/response.js:361:21)
```

**Comment by AdriVanHoudt** [comment]
wait isn' this `no milestone found for milestone in title of issue`? since https://github.com/hapijs/hapijs.com/blob/master/lib/changelog.js#L209

**Comment by Marsup** [comment]
There was actually 2 stack traces, copied the wrong one.

**Comment by Marsup** [comment]
Closing until this happens again in case #288 fixed this.
