### ISSUE TITLE
Connection error unhandled on changelog.getMilestoneNumberFromTitle

### ISSUE THREAD

**Issue by Marsup** [hapijs/hapijs.com#288]
```
Debug: internal, implementation, error
    TypeError: Uncaught error: Cannot read property 'length' of undefined
    at lib/changelog.js:219:43
    at lib/utils.js:59:20
    at node_modules/async/lib/async.js:750:21
    at node_modules/async/lib/async.js:167:37
    at lib/utils.js:41:24
    at node_modules/wreck/lib/index.js:450:20
    at finish (node_modules/wreck/lib/index.js:309:16)
    at wrapped (node_modules/hoek/lib/index.js:798:20)
    at onReaderFinish (node_modules/wreck/lib/index.js:346:16)
    at g (events.js:180:16)
```

**Comment by Marsup** [comment]
Maybe #287 is a consequence of this.
