### ISSUE TITLE
Error trying to start application

### ISSUE THREAD

**Issue by nrodriguez** [hapijs/hapijs.com#597]
When running `npm start` on a fresh clone after running `npm i` and `make`. It throws this error

```
Unhandled Rejection at: Promise {
  <rejected> { AssertionError [ERR_ASSERTION]: Invalid plugin options {
  "plugin": {
    "register": function (server, options, next) {\n    var config = hoek.applyToDefaults({\n        script: 'npm run build',\n        cwd: process.cwd(),\n        verbose: false\n    }, options || {});\n\n    if (options.verbose) {\n        process.env.DEBUG = \"bss:*,\" + (process.env.DEBUG || \"\");\n    } else {\n        process.env.DEBUG = \"bss:info,bss:warn,bss:error,\" + (process.env.DEBUG || \"\");\n    }\n\n    var debugPlugin   = require('debug')('bss:plugin');\n    var debugRunner   = require('debug')('bss:runner');\n    var debugWatcher  = require('debug')('bss:watch ');\n    var debugNotifier = require('debug')('bss:notify');\n    var debugReload   = require('debug')('bss:reload');\n\n    var livereload = require('./lr-notify');\n    var logger = require('./loggers');\n\n    var filesRequested = {};\n    var filesLivereloaded = {};\n    var buildLock = false;\n    var lastBuildEnd = 0;\n\n    var buildStatus;\n\n    var resetBuildStatus = function () {\n        buildStatus = {\n            filesReloaded: {\n            }\n        };\n    };\n    resetBuildStatus();\n\n    debugRunner(\"starting\");\n    var runner = new Runner({\n        cmd: function (done) {\n            debugRunner(\"spawning command\");\n            var args = config.script.split(' ');\n            var cmd = args.shift();\n            var ps = spawn(cmd, args);\n            var err = '';\n\n            ps.stderr.on('data', function (d) {\n                d = d.toString();\n                err += d;\n            });\n\n            ps.stdout.pipe(sculpt.split('\\n'))\n                     .pipe(sculpt.prepend('    '))\n                     .pipe(sculpt.append('\\n'))\n                     .pipe(process.stdout);\n\n            ps.on('close', function () {\n\n                if (err.length > 0) {\n                    debugRunner(\"command complete with errors\");\n                    if (err.match(/npm ERR!/)) {\n                        err = err.substr(0, err.indexOf(\"npm ERR!\"));\n                    }\n\n                    err.split('\\n').map(function (line) {\n                        if (line.trim().length > 0) {\n                           logger.error(line.red);\n                        }\n                    });\n                } else {\n                    debugRunner(\"command complete\");\n                }\n                done();\n            });\n        }\n    });\n\n    var notifyFile = function(file) {\n        file = path.basename(file);\n\n        if (Object.keys(filesRequested).length === 0) {\n            debugNotifier('No files requested yet, triggering full refresh');\n            file = 'index.html';\n        }\n\n        if (file.match(/css$/) && !filesRequested[file]) {\n            return debugNotifier('File ' + file + ' has never been loaded, skipping');\n        }\n\n        if (buildStatus.filesReloaded[file]) {\n            return debugNotifier('File ' + file + ' already reloaded');\n        }\n\n        if (file.match(LIVERELOADABLE_REGEX)) {\n            logger.info('Live reloading: ' + file);\n            debugNotifier('Live reloading: ' + file);\n            buildStatus.filesReloaded[file] = true;\n            filesLivereloaded[file] = true;\n            livereload.notify(file);\n            return;\n        }\n\n        debugNotifier('Checking ' + file + ' against extra livereload config');\n        Object.keys(EXTRA_LIVERELOAD_MAP).forEach(function (key) {\n            var reloadFile = EXTRA_LIVERELOAD_MAP[key];\n            var regex = new RegExp(key.slice(1,-1));\n            if (file.match(regex)) {\n                debugNotifier(file + ' matches ' + regex + ': reloading ' + reloadFile);\n                notifyFile(reloadFile);\n            } else {\n                debugNotifier(file + ' does not match ' + regex);\n            }\n        });\n\n    };\n\n    var buildStart;\n\n    runner.on('run:start', function () { buildLock = true; })\n          .on('run:end', function () { buildLock = false; })\n          //For build timing\n          .on('run:queued', function () {\n              logger.info('Build queued');\n              debugRunner('vvvvvvvvv queued new build vvvvvvvv');\n              resetBuildStatus();\n              buildStart = Date.now();\n          })\n          .on('run:start', function () {\n              logger.info('Build started');\n              debugRunner('---------- started build ---------');\n\n          })\n          .on('run:end', function () {\n              var runTime = Date.now() - buildStart;\n              var runTimeS = (runTime/1000).toString().substr(0,5) + 's';\n              logger.info('Built in', runTimeS);\n              debugRunner('^^^^^^^^^ build ran in ' + runTimeS + ' ^^^^^^^^');\n              lastBuildEnd = Date.now();\n          });\n\n    var handleChangedFile = function (changeType, f) {\n        debugWatcher(changeType + ': ' + f);\n        if (buildLock) {\n            debugWatcher('build already running');\n        } else {\n            isFileOlderThan(f, lastBuildEnd, function (err, older) {\n                if (err) { console.error(err); }\n\n                if (older) {\n                    debugWatcher(f + ' was from previous build, notifying');\n                    notifyFile(f);\n                } else {\n                    runner.queue();\n                    notifyFile(f);\n                }\n            });\n        }\n    };\n\n    server.ext('onPreHandler', function (request, done) {\n        runner.delayIfRunning(done);\n    });\n\n    try {\n        debugPlugin(\"Adding * path to hapi server\");\n        server.route({\n            path: '/{path*}',\n            method: 'GET',\n            handler: {\n                directory: {\n                    path: config.cwd + '/'\n                }\n            }\n        });\n    } catch (e) {\n        logger.warn('Hapi server already has a /{path*}, ignoring');\n    }\n\n    server.on('response', function (resp) {\n        var basename = path.basename(resp.path);\n        if (buildStatus.filesReloaded[basename]) {\n            debugReload(basename + \" reloaded in \" + (Date.now() - buildStart)/1000 + 's since build start');\n            logger.info(basename + \" reloaded in \" + (Date.now() - buildStart)/1000 + 's (since build start)');\n        }\n        if (basename.match(LIVERELOADABLE_REGEX)) {\n            filesRequested[basename] = true;\n        }\n    });\n\n    var watcher = fileWatcher(process.cwd());\n\n    watcher.on('error', function (err) {\n        throw err;\n    });\n\n    watcher.on('log', function (msg) {\n        debugWatcher(msg);\n    });\n\n    watcher.on('ready', function () {\n        watcher.on('change', handleChangedFile.bind(handleChangedFile, 'changed'));\n\n        debugReload('Starting livereload server');\n        livereload.startServer(function (err) {\n            if (err) {\n                logger.error('Error starting livereload server.'.red);\n                logger.error('This is probably because you are running the livereload mac app.');\n                logger.error('Please close it and try again.');\n                logger.error(\"Full error: [\" + err.code + \"] \" + err.message);\n                process.exit();\n            }\n\n            debugPlugin('Building static server plugin loaded');\n            runner.queue();\n            runner.once('run:end', next);\n        });\n    });\n},
    "name" [1]: -- missing --
  }
}

[1] "name" is required
    at new AssertionError (internal/errors.js:470:11)
    at Object.exports.assert (/Users/nrodriguez/Documents/Projects/hapijs.com/node_modules/hoek/lib/index.js:736:11)
    at Object.exports.apply (/Users/nrodriguez/Documents/Projects/hapijs.com/node_modules/hapi/lib/config.js:22:10)
    at internals.Server.register (/Users/nrodriguez/Documents/Projects/hapijs.com/node_modules/hapi/lib/server.js:399:31)
    at process._tickCallback (internal/process/next_tick.js:178:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' } } reason: { AssertionError [ERR_ASSERTION]: Invalid plugin options {
  "plugin": {
    "register": function (server, options, next) {\n    var config = hoek.applyToDefaults({\n        script: 'npm run build',\n        cwd: process.cwd(),\n        verbose: false\n    }, options || {});\n\n    if (options.verbose) {\n        process.env.DEBUG = \"bss:*,\" + (process.env.DEBUG || \"\");\n    } else {\n        process.env.DEBUG = \"bss:info,bss:warn,bss:error,\" + (process.env.DEBUG || \"\");\n    }\n\n    var debugPlugin   = require('debug')('bss:plugin');\n    var debugRunner   = require('debug')('bss:runner');\n    var debugWatcher  = require('debug')('bss:watch ');\n    var debugNotifier = require('debug')('bss:notify');\n    var debugReload   = require('debug')('bss:reload');\n\n    var livereload = require('./lr-notify');\n    var logger = require('./loggers');\n\n    var filesRequested = {};\n    var filesLivereloaded = {};\n    var buildLock = false;\n    var lastBuildEnd = 0;\n\n    var buildStatus;\n\n    var resetBuildStatus = function () {\n        buildStatus = {\n            filesReloaded: {\n            }\n        };\n    };\n    resetBuildStatus();\n\n    debugRunner(\"starting\");\n    var runner = new Runner({\n        cmd: function (done) {\n            debugRunner(\"spawning command\");\n            var args = config.script.split(' ');\n            var cmd = args.shift();\n            var ps = spawn(cmd, args);\n            var err = '';\n\n            ps.stderr.on('data', function (d) {\n                d = d.toString();\n                err += d;\n            });\n\n            ps.stdout.pipe(sculpt.split('\\n'))\n                     .pipe(sculpt.prepend('    '))\n                     .pipe(sculpt.append('\\n'))\n                     .pipe(process.stdout);\n\n            ps.on('close', function () {\n\n                if (err.length > 0) {\n                    debugRunner(\"command complete with errors\");\n                    if (err.match(/npm ERR!/)) {\n                        err = err.substr(0, err.indexOf(\"npm ERR!\"));\n                    }\n\n                    err.split('\\n').map(function (line) {\n                        if (line.trim().length > 0) {\n                           logger.error(line.red);\n                        }\n                    });\n                } else {\n                    debugRunner(\"command complete\");\n                }\n                done();\n            });\n        }\n    });\n\n    var notifyFile = function(file) {\n        file = path.basename(file);\n\n        if (Object.keys(filesRequested).length === 0) {\n            debugNotifier('No files requested yet, triggering full refresh');\n            file = 'index.html';\n        }\n\n        if (file.match(/css$/) && !filesRequested[file]) {\n            return debugNotifier('File ' + file + ' has never been loaded, skipping');\n        }\n\n        if (buildStatus.filesReloaded[file]) {\n            return debugNotifier('File ' + file + ' already reloaded');\n        }\n\n        if (file.match(LIVERELOADABLE_REGEX)) {\n            logger.info('Live reloading: ' + file);\n            debugNotifier('Live reloading: ' + file);\n            buildStatus.filesReloaded[file] = true;\n            filesLivereloaded[file] = true;\n            livereload.notify(file);\n            return;\n        }\n\n        debugNotifier('Checking ' + file + ' against extra livereload config');\n        Object.keys(EXTRA_LIVERELOAD_MAP).forEach(function (key) {\n            var reloadFile = EXTRA_LIVERELOAD_MAP[key];\n            var regex = new RegExp(key.slice(1,-1));\n            if (file.match(regex)) {\n                debugNotifier(file + ' matches ' + regex + ': reloading ' + reloadFile);\n                notifyFile(reloadFile);\n            } else {\n                debugNotifier(file + ' does not match ' + regex);\n            }\n        });\n\n    };\n\n    var buildStart;\n\n    runner.on('run:start', function () { buildLock = true; })\n          .on('run:end', function () { buildLock = false; })\n          //For build timing\n          .on('run:queued', function () {\n              logger.info('Build queued');\n              debugRunner('vvvvvvvvv queued new build vvvvvvvv');\n              resetBuildStatus();\n              buildStart = Date.now();\n          })\n          .on('run:start', function () {\n              logger.info('Build started');\n              debugRunner('---------- started build ---------');\n\n          })\n          .on('run:end', function () {\n              var runTime = Date.now() - buildStart;\n              var runTimeS = (runTime/1000).toString().substr(0,5) + 's';\n              logger.info('Built in', runTimeS);\n              debugRunner('^^^^^^^^^ build ran in ' + runTimeS + ' ^^^^^^^^');\n              lastBuildEnd = Date.now();\n          });\n\n    var handleChangedFile = function (changeType, f) {\n        debugWatcher(changeType + ': ' + f);\n        if (buildLock) {\n            debugWatcher('build already running');\n        } else {\n            isFileOlderThan(f, lastBuildEnd, function (err, older) {\n                if (err) { console.error(err); }\n\n                if (older) {\n                    debugWatcher(f + ' was from previous build, notifying');\n                    notifyFile(f);\n                } else {\n                    runner.queue();\n                    notifyFile(f);\n                }\n            });\n        }\n    };\n\n    server.ext('onPreHandler', function (request, done) {\n        runner.delayIfRunning(done);\n    });\n\n    try {\n        debugPlugin(\"Adding * path to hapi server\");\n        server.route({\n            path: '/{path*}',\n            method: 'GET',\n            handler: {\n                directory: {\n                    path: config.cwd + '/'\n                }\n            }\n        });\n    } catch (e) {\n        logger.warn('Hapi server already has a /{path*}, ignoring');\n    }\n\n    server.on('response', function (resp) {\n        var basename = path.basename(resp.path);\n        if (buildStatus.filesReloaded[basename]) {\n            debugReload(basename + \" reloaded in \" + (Date.now() - buildStart)/1000 + 's since build start');\n            logger.info(basename + \" reloaded in \" + (Date.now() - buildStart)/1000 + 's (since build start)');\n        }\n        if (basename.match(LIVERELOADABLE_REGEX)) {\n            filesRequested[basename] = true;\n        }\n    });\n\n    var watcher = fileWatcher(process.cwd());\n\n    watcher.on('error', function (err) {\n        throw err;\n    });\n\n    watcher.on('log', function (msg) {\n        debugWatcher(msg);\n    });\n\n    watcher.on('ready', function () {\n        watcher.on('change', handleChangedFile.bind(handleChangedFile, 'changed'));\n\n        debugReload('Starting livereload server');\n        livereload.startServer(function (err) {\n            if (err) {\n                logger.error('Error starting livereload server.'.red);\n                logger.error('This is probably because you are running the livereload mac app.');\n                logger.error('Please close it and try again.');\n                logger.error(\"Full error: [\" + err.code + \"] \" + err.message);\n                process.exit();\n            }\n\n            debugPlugin('Building static server plugin loaded');\n            runner.queue();\n            runner.once('run:end', next);\n        });\n    });\n},
    "name" [1]: -- missing --
  }
}

[1] "name" is required
    at new AssertionError (internal/errors.js:470:11)
    at Object.exports.assert (/Users/nrodriguez/Documents/Projects/hapijs.com/node_modules/hoek/lib/index.js:736:11)
    at Object.exports.apply (/Users/nrodriguez/Documents/Projects/hapijs.com/node_modules/hapi/lib/config.js:22:10)
    at internals.Server.register (/Users/nrodriguez/Documents/Projects/hapijs.com/node_modules/hapi/lib/server.js:399:31)
    at process._tickCallback (internal/process/next_tick.js:178:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
```

```
⬢  hapijs.com  master ⦾ node -v
v10.0.0
⬢  hapijs.com  master ⦾ npm -v
6.1.0
```

**Comment by sitrakary** [comment]
This is caused by the package `building-static-server` which does not supports hapi v17

**Comment by Nargonath** [comment]
Pretty strange I don't have this issue at all. I'm on OSX 10.13.6 with:
![image](https://user-images.githubusercontent.com/583657/46831853-d368ee00-cda4-11e8-8fbb-37d9bef9bf11.png)

If you update every thing do you still have the same problem? What system are you running this on?

**Comment by nrodriguez** [comment]
@Nargonath Still receiving the same error on OSX 10.13.6

```
⬢  hapijs.com  master ⦾ npm -v
6.4.1
⬢  hapijs.com  master ⦾ node -v
v10.12.0
```

**Comment by Nargonath** [comment]
That's pretty weird ...
